### ISSUE TITLE
Error after upgrade to v4.0

### ISSUE THREAD

**Issue by clementizard** [marnusw/react-css-transition-replace#65]
Hello!
I have an issue after the v4 upgrade regarding dom-helpers:  Cannot find module 'dom-helpers/util/requestAnimationFrame'

Here is my config:
react: 16.10.1
react-css-transition-replace: 4.0.0

I tried to install dom-helpers (v5.1.0) but it didn't changed. After that i've searched in your package.json and found you already use it.

So i ran through their package and found out there is no "utils" folder. It seems to be renamed to "dom-helpers/animationFrame" and has to be used like:
"animationFrame.request(cb) returns an ID for canceling"

I did the change in the ReactCssTransitionReplace.js file, and there is another error occuring: "Cannot find module 'dom-helpers/class/addClass'"

I guess this is the same error pattern as the previous one, but i have to go to work so i can't continue to investigate on this for now.

In the meantime if you have an idea on how to fix that, i'd appreciate it :) 

Anyway, cheers for the excellent work!

EDIT:
So i continued to change imports to match files of dom-helpers package, ended up with something like this in ReactCssTransitionReplaceChild.js:

```
import addClass from 'dom-helpers/addClass'
import removeClass from 'dom-helpers/removeClass'
import animationFrame from 'dom-helpers/animationFrame'
import transitionEnd from 'dom-helpers/transitionEnd'
```
And removed line 21 to 23. I'm not sure about TransitionEnd, as it completely delete animationEnd event.

Anyway, it does compile... until dom-helpers uses "window" and breaks my ssr.

So i'm rolling back to 3.0.3 until we solve this issue.

EDIT 2:
Possible solution: maybe rollback dom-helpers to the last working version (^3.3.1)?

**Comment by w33ble** [comment]
Can confirm. In v3, you used [dom-helpers@^3.3.1](https://github.com/marnusw/react-css-transition-replace/blob/v3.0.3/package.json#L20)

In v4, you upgraded to [dom-helpers@^5.1.0](https://github.com/marnusw/react-css-transition-replace/blob/master/packages/react-css-transition-replace/package.json#L23)

As of `dom-helpers@5.0.0`, [there are no more subdirectories](https://github.com/react-bootstrap/dom-helpers/tree/v5.0.0/src).

**Comment by marnusw** [comment]
Thank you both for your investigations. I guess this is a pitfall of using a monorepo! Sorry about the inconvenience caused. Let me know if there are still issues with `4.0.1`.

**Comment by w33ble** [comment]
Sure thing. I’m still curious why the demo ends up only using the older version of dom-helpers. I haven’t seen yarn get that wrong before, so this has me worried about some of my own packages... 

I think @clementizard was on the better path, it would be nice to upgrade dom-helpers, but neither of us is familiar enough with it to update the animation changes.

**Comment by marnusw** [comment]
@w33ble I also started the upgrade to v5 this morning but then bailed when it took too long and figured it's better to get the fix out asap. I will definitely look at upgrading dom-helpers at some point. I also need to take out `UNSAFE_componentWillReceiveProps` at some point!
